  
[window]
dynamic_padding = true
padding.x = 4
padding.y = 4
opacity = 0.8
blur = true

[font]
normal.family = "CaskaydiaCove Nerd Font"
size = 12

# [keyboard]
# bindings = [
#   { key = "Right", mods = "Alt", chars = "\u001BF" },
#   { key = "Left",  mods = "Alt", chars = "\u001BB" },
# ]

[general]
import = [
  "~/.config/alacritty/catppuccin_mocha.toml"
]
