windowrule = suppressevent maximize, class:.* # You'll probably like this.
windowrule = float,class:(org.pulseaudio.pavucontrol),title:^(Volume Control)$ 
windowrule = float,class:(com.saivert.pwvucontrol),title:^(Pipewire Volume Control)$ 
windowrule = float,class:(brave),title:^(Open File)$
windowrule = float,class:(brave),title:^(Save File)$
windowrule = float,class:(xdg-desktop-portal-gtk),title:(.*)(wants to open)
windowrule = float,class:(xdg-desktop-portal-gtk),title:(.*)(wants to save)
windowrule = workspace 10 silent,class:^(Docker Desktop)$

# JetBrains flicker fix
windowrule = noinitialfocus,class:(jetbrains-)(.*),title:^win(.*), initialTitle:win.*, floating:1  
windowrule = workspace 1 silent,class:^(jetbrains-phpstorm)$
