# --- Global behavior ---
windowrule {
  name = suppress-maximize
  match:class = .*

  suppress_event = maximize
}

# --- Volume control apps ---
windowrule {
  name = volume-float
  match:class = (org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)
  match:title = ^(Volume Control|Pipewire Volume Control)$

  float = on
}

# --- File dialogs (Brave + portals) ---
windowrule {
  name = file-dialogs
  match:title = ^(Open File|Save File)$

  float = on
}

windowrule {
  name = portal-dialogs
  match:class = xdg-desktop-portal-gtk
  match:title = (.*)(wants to (open|save))

  float = on
}

# --- JetBrains fixes ---
windowrule {
  name = jetbrains-flicker-fix
  match:class = (jetbrains-)(.*)
  match:initial_title = ^win(.*

  no_initial_focus = on
}

