##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule 
# windowrule = float,class:^(kitty)$,title:^(kitty)$

windowrule = suppressevent maximize, class:.* # You'll probably like this.
windowrule = float,class:(org.pulseaudio.pavucontrol),title:^(Volume Control)$ 
windowrule = float,class:(brave),title:^(Open File)$
windowrule = float,class:(brave),title:^(Save File)$
windowrule = float,class:(xdg-desktop-portal-gtk),title:(.*)(wants to open)
windowrule = float,class:(xdg-desktop-portal-gtk),title:(.*)(wants to save)
windowrule = workspace 10 silent,class:^(Docker Desktop)$

# JetBrains flicker fix
windowrule = noinitialfocus,class:(jetbrains-)(.*),title:^win(.*), initialTitle:win.*, floating:1  
windowrule = workspace 1 silent,class:^(jetbrains-phpstorm)$
